services:
  ping-exporter:
    image: destrebecqclara/ping-exporter:v1.0.0
    ports:
      - 8000:80
    environment:
      - PORT=80

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9000:9090

  grafana:
    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000




